import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Main from "../components/mainPage/main/main";
import About from "../components/mainPage/about/about";
import Experience from "../components/mainPage/experience/experience";
import Product from "../components/mainPage/product/product";
import Contact from '../components/mainPage/contact/contact';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Main />
        <About />
        <Experience />
        <Product />
        <Contact />
      </main>
      
    </div>
  )
}
